<?php
/**
 * TicketQuery
 * @version     1.0
 * @license     http://mit-license.org/
 * @coder       Yevhenii Pylypenko <i.pylypenko@hexa.com.ua>
 * @coder       Alexander Oganov   <a.ohanov@hexa.com.ua>
 * @copyright   Copyright (C) Hexa,  All rights reserved.
 */

namespace hexa\yiisupport\db;

/**
 * Class TicketQuery
 */
class TicketQuery extends ActiveQuery
{
    public function alias($alias)
    {
        return parent::alias($alias); // TODO: Change the autogenerated stub
    }


    /**
     * @param integer $id
     *
     * @return $this
     */
    public function byTicketId($id)
    {
        return $this->byAttribute('ticket_id', $id);
    }

    /**
     * @param integer $id
     *
     * @return $this
     */
    public function byUserId($id)
    {
        return $this->byAttribute('created_by', $id);
    }

    /**
     * @param bool $isResolved
     *
     * @return $this
     *
     */
    public function resolved($isResolved = true)
    {
        return $this->andOnCondition(['T.status_id' => 'TS.id'])->andOnCondition(['TS.resolve' => (int)$isResolved]);
    }
}
